# Workout 3

# This document contains R functions for the package "binomial"
# There are three types of functions:
# private: auxiliary functions not intended to be called by the user
# main: main functions that the user is expected to invoke
# methods: public functions that support classes of objects generated by some of the main functions

### 1.1) Private Checker Functions

# Auxiliary function check_prob(): checks whether the input probability is valid

check_prob = function(prob){
  if(prob <= 1 & prob >= 0){
    return(TRUE)
  }
  else{
    stop("invalid probability value")
  }
}

# Auxiliary function check_trials(): checks whether the input number of trials is valid

check_trials = function(trials){
  if((trials > 0) & (trials%%1 == 0 )){
    return(TRUE)
  }
  else{
    stop("invalid trials value")
  }

}

# Auxiliary function check_success() : checks whether the input number of succcesses is valid

check_success = function(success, trials){
  if(check_trials(success) & check_trials(trials) & (success<= trials)) {
    return(TRUE)
  }
  else{
    stop("invalid success value")
  }
}

### 1.2) Private Auxiliary Functions

# aux_mean is a private auxiliary function that returns the expected value of the binomial distribution

aux_mean = function(trials, prob) {
  mean = trials * prob
  return(mean)
}

# aux_variance is a function that returns the variance of the binomial distribution

aux_variance = function(trials, prob) {
  variance = trials * prob * (1-prob)
  return(variance)
}

# aux_mode is a function that returns the mode of the experiment

aux_mode = function(trials, prob){
  val = (trials + 1) * prob
  if (as.integer(val) == val){
    mode_1 = val
    mode_2 = mode1 - 1
    return (c(mode_1, mode_2))
  }
  else{
    mode = floor(val)
    return(mode)
  }
}

# aux_skewness is a function that returns the skewness of a probability distribution

aux_skewness = function(trials, prob){
  skewness = (1-2*prob)/sqrt(trials*prob*(1-prob))
  return(skewness)
}

# aux_kurtosis is a function that returns the shape of a probability distribution

aux_kurtosis = function(trials, prob){
  kurtosis = (1- ((6*prob)*(1-prob)))/((trials*prob)*(1-prob))
  return(kurtosis)
}

### 1.3

#' @title binomial choose factor
#' @description calculates the number of combinations of k successes that occur in n trials
#' @param n number of trials
#' @param k number of successes
#' @return number of combinations of k successes that occur in n trials
#' @export
#' @examples
# bin_choose(n = 5, k = 2)
# 5 choose 1:3
# bin_choose(5, 1:3)

bin_choose = function(n,k){
  if(check_success(k,n)){
    choose = (factorial(n))/(factorial(k)*factorial(n-k))
    return (choose)
  }
  else{
    stop("invalid input")
  }
}

### 1.4

#' @title Binomial Probability
#' @description Calculates the probability of success given the number of trials, successes, and probability
#' @param success numeric value for number of successes
#' @param trials number of trials
#' @param prob probability of success
#' @return computed binomial probability
#' @export
#' @examples
#' # probability of getting 2 successes in 5 trials with probability 0.5
#' bin_probability(success = 2, trials = 5, prob = 0.5)
#' # probabilities of getting 2 or less successes in 5 trials with probability 0.5
#' bin_probability(success = 0:2, trials = 5, prob = 0.5)

bin_probability = function(success, trials, prob){

  if (check_trials(trials) != TRUE){
    stop("invalid trials value")
  }
  else if (check_prob(prob) != TRUE){
    stop("invalid probability value")
  }
  else if (check_success(success, trials) != TRUE){
    stop("invalid success value")
  }
  else{
    binomial = bin_choose(trials,success) * (prob^success )* ((1-prob)^(trials-success))
    return(binomial)
  }
}

### 1.5
#' @title Binomial Distribution
#' @description  Calculates the probability of success trials
#' @param trials number of trials
#' @param prob probability of success
#' @return number of successes and probability
#' @export
#' @examples
#' bin_distribution(trials = 5, probability = 0.5)

bin_distribution <- function(trials, prob){
  probability <- c()
  if (check_prob(prob) & check_trials(trials)) {
    for (i in c(0:trials)) {
      probability[i+1] = bin_probability(i,trials,prob)
    }
    success <- c(0:trials)
    probability_table <- data.frame(cbind(success,probability))
    class(probability_table) <- c("bindist","data.frame")
    return(probability_table)
  }
}

#' @export
plot.bindist <- function(object){
  barplot(object$probability, width = 0.6, xlab = "successes", ylab = "probability", names.arg = c(0:max(object$success)))
}

### 1.6
#' @title Binomial Cumulative distribution
#' @description calculates the probability and cumulative probability of successes given the number of trials probability
#' @param trials number of trials
#' @param prob probability of success
#' @return a data frame with number of success, probabilty and cumulative probability
#' @export
#' @examples
#' bin_cumulative(trials = 5, probability = 0.5)
#' dis2 <- bin_cumulative(trials = 5, prob = 0.5)
#' plot(dis2)

bin_cumulative <- function(trials, prob){
  bin <- bin_distribution(trials,prob)
  cumulative <- c()
  for (i in c(1:length(bin$probability))){
    if (i==1){
      cumulative[i] <- bin$probability[i]
    }
    else{
      cumulative[i]<-cumulative[i-1] + bin$probability[i]
    }
  }
  bin$cumulative <- cumulative
  class(bin_dist)<- c("bincum","data.frame")
  return(bin_dist)
}
### Function plot_bincum

#' @export
plot.bincum <- function(x){
  library(ggplot2)
  bincum <- ggplot(data = x, aes(x= success, y = cumulative)) + geom_line() + geom_point(shape = 1, size = 2) + labs(x = "success", y = "")
  return(bincum)
}

### 1.7
#' @title Binomial Random Variable
#' @description calculates cumulative binomial distribution given the number of trials and probability
#' @param trials number of trials
#' @param prob probability of success
#' @return A Binomial Random Variable object
#' @export
#' @examples
#` bin_variable(trials = 10, p = 0.3)

bin_variable <- function(trials, prob){
  if (check_trials(trials) != TRUE){
    stop("invalid trials value")
  }
  if (check_prob(prob) != TRUE){
    stop("invalid prob value")
  }
  binvar <- list(trials = trials, prob = prob)
  class(binvar) <-  c("binvar")
  return(binvar)
}

#'@export
print.binvar = function(x) {
  cat('"Binomial variable"')
  cat("\n\n")
  cat("Parameters\n")
  cat("- Number of trials:", x$trials, "\n")
  cat("- Prob of success:", x$prob)
}

#'@export
summary.binvar <- function(x){
  dat <- data.frame(
    trials = x$trials,
    prob = x$prob,
    mean = aux_mean(x$trials, x$prob),
    variance = aux_variance(x$trials, x$prob),
    mode = aux_mode(x$trials, x$prob),
    skewness = aux_skewness(x$trials, x$prob),
    kurtosis = aux_kurtosis(x$trials, x$prob)
    )
  x = list(dat)
  class(dat) <- c("summary.binvar", "list")
  return(x)
}



print.summary.binvar <- function(x) {
  cat('"Binomial variable"')
  cat("\n\n")
  cat("Parameters")
  cat("\n", "- trials:", x$trials)
  cat("\n\n")
  cat("\n", "- prob:", x$prob)
  cat("\n\n")
  cat("Measures")
  cat("\n", "- mean:", x$mean)
  cat("\n", "- variance:", x$variance)
  cat("\n", "- mode:", x$mode)
  cat("\n", "- skewness:", x$skewness)
  cat("\n", "- kurtosis:", x$kurtosis)
}

### 1.8
#' @title Binomial Mean
#' @description Calculates the expected value of Binomial Distribution
#' @param trials number of trials
#' @param prob probability of success
#' @return computed binomial mean
#' @export
#' @examples
#' bin_mean(trials = 10, prob = 0.2)

bin_mean <- function(trials, prob){
  if (check_trials(trials) != TRUE){
    stop("invalid trials value")
  }
  if (check_prob(prob) != TRUE){
    stop("invalid prob value")
  }
  else{
    return(aux_mean(trials, prob))
  }
}

#' @title Binomial Variance
#' @description Calculates the variance of the binomial distribution
#' @param trialsnumber of trials
#' @param prob probability of success
#' @return computed binomial variance
#' @export
#' @examples
#' bin_variance(trials = 10, prob = 0.2)

bin_variance <- function(trials, prob){
  if (check_trials(trials) != TRUE){
    stop("invalid trials value")
  }
  else if (check_prob(prob) != TRUE){
    stop("invalid prob value")
  }
  else{
    return(aux_variance(trials, prob))
  }
}

#' @title binomial mode
#' @description computes the mode of the binomial experiment
#' @param trials numeric value for the number of trials
#' @param prob numeric value for the probability of success
#' @return computed binomial mode
#' @export
#' @examples
#' bin_mode(trials = 10, prob = 0.3)

bin_mode = function(trials, prob){
  if (check_trials(trials) != TRUE){
    stop("invalid trials value")
  }
  else if (check_prob(prob) != TRUE){
    stop("invalid prob value")
  }
  else{
    return(aux_mode(trials, prob))
  }
}

#' @title Binomial Skewness
#' @description Calculates the skewness of the binomial distribution
#' @param trials number of trials
#' @param prob probability of success
#' @return computed binomial skewness
#' @export
#' @examples
#' bin_skewness(trials = 10, prob = 0.2)

bin_skewness <- function(trials, prob){
  if (check_trials(trials) != TRUE){
    stop("invalid trials value")
  }
  else if (check_prob(prob) != TRUE){
    stop("invalid prob value")
  }
  else{
    return(aux_skewness(trials, prob))
  }
}

#' @title Binomial Kurtosis
#' @description Computes the kurtosis of the binomial distribution
#' @param trials number of trials
#' @param prob probability of success
#' @return computed binomial kurtosis
#' @export
#' @examples
#' bin_kurtosis(trials = 10, prob = 0.2)

bin_kurtosis = function(trials, prob){
  if (check_trials(trials) != TRUE){
    stop("invalid trials value")
  }
  else if (check_prob(prob) != TRUE){
    stop("invalid prob value")
  }
  else{
    return(aux_kurtosis(trials, prob))
  }
}

